"""Lingo built-in function and property name tables.

Used by the decompiler to resolve the `the <prop>`, built-in calls,
and command names that Director maps by numeric ID.
"""

from __future__ import annotations

# Built-in "the" properties (theBuiltin opcode)
THE_BUILTINS: dict[int, str] = {
    0x00: "floatPrecision",
    0x01: "mouseDownScript",
    0x02: "mouseUpScript",
    0x03: "keyDownScript",
    0x04: "keyUpScript",
    0x05: "timeoutScript",
    0x06: "short time",
    0x07: "abbr time",
    0x08: "long time",
    0x09: "abbr date",
    0x0A: "short date",
    0x0B: "long date",
    0x0C: "lastEvent",
    0x0D: "lastClick",
    0x0E: "lastRoll",
    0x0F: "lastKey",
    0x10: "lastFrame",
    0x11: "timer",
    0x12: "ticks",
    0x13: "currentTime",
    0x14: "key",
    0x15: "keyCode",
    0x16: "mouseV",
    0x17: "mouseH",
    0x18: "mouseDown",
    0x19: "mouseUp",
    0x1A: "menu",
    0x1B: "scriptNum",
    0x1C: "castMembers",  # the number of castMembers
    0x1D: "previousCastNum",
    0x1E: "pathName",
    0x1F: "movieName",
    0x20: "stageColor",
    0x21: "loaded",
    0x22: "selection",
    0x23: "selEnd",
    0x24: "selStart",
    0x25: "freeBytes",
    0x26: "freeBlock",
    0x27: "preLoadRAM",
    0x28: "multiSound",
    0x29: "alertHook",
    0x2A: "soundEnabled",
    0x2B: "soundLevel",
    0x2C: "soundActive1",
    0x2D: "soundActive2",
    0x2E: "lastChannel",
    0x2F: "activeWindow",
    0x30: "stageLeft",
    0x31: "stageTop",
    0x32: "stageRight",
    0x33: "stageBottom",
    0x34: "paramCount",
    0x35: "borderSize",
    0x36: "border",
    0x37: "constraint",
    0x38: "cursor",
    0x39: "immediate",
    0x3A: "ink",
    0x3B: "itemDelimiter",
    0x3C: "lineSize",
    0x3D: "locH",
    0x3E: "locV",
    0x3F: "movieFileFreeSize",
    0x40: "movieFileSize",
    0x41: "number",
    0x42: "result",
    0x43: "rollOver",
    0x44: "stageWindow",
    0x45: "visible",
    0x46: "volume",
    0x47: "machineType",
    0x48: "platform",
    0x49: "colorDepth",
    0x4A: "videoForWindowsPresent",
    0x4B: "quickTimePresent",
    0x4C: "emulateMultiButton",
}


# Known built-in command names (ext calls that are Lingo builtins).
# Used to recognise built-in functions vs user-defined handlers.
EXT_CALL_BUILTINS: frozenset[str] = frozenset(
    {
        "go",
        "play",
        "playDone",
        "updateStage",
        "puppetSprite",
        "puppetSound",
        "puppetTransition",
        "puppetPalette",
        "puppetTempo",
        "alert",
        "cursor",
        "delay",
        "do",
        "halt",
        "hilite",
        "nothing",
        "pass",
        "put",
        "quit",
        "restart",
        "shutDown",
        "startTimer",
        "sound",
        "open",
        "beep",
        "moveableSprite",
        "openDA",
        "printFrom",
        "installMenu",
    }
)


# Sprite property names (getObjProp / setObjProp on sprites)
SPRITE_PROPERTIES: dict[int, str] = {
    0x01: "type",
    0x02: "backColor",
    0x03: "bottom",
    0x04: "castNum",
    0x05: "constraint",
    0x06: "cursor",
    0x07: "foreColor",
    0x08: "height",
    0x09: "immediate",
    0x0A: "ink",
    0x0B: "left",
    0x0C: "lineSize",
    0x0D: "locH",
    0x0E: "locV",
    0x0F: "movieRate",
    0x10: "movieTime",
    0x11: "pattern",
    0x12: "puppet",
    0x13: "right",
    0x14: "startTime",
    0x15: "stopTime",
    0x16: "stretch",
    0x17: "top",
    0x18: "trails",
    0x19: "visible",
    0x1A: "volume",
    0x1B: "width",
    0x1C: "blend",
    0x1D: "scriptNum",
    0x1E: "moveableSprite",
    0x1F: "editableText",
    0x20: "scoreColor",
    0x21: "loc",
    0x22: "rect",
    0x23: "memberNum",
    0x24: "castLibNum",
    0x25: "member",
    0x26: "scriptInstanceList",
    0x27: "currentTime",
    0x28: "mostRecentCuePoint",
    0x29: "tweened",
    0x2A: "name",
}

# Movie/cast member properties
MEMBER_PROPERTIES: dict[int, str] = {
    0x01: "name",
    0x02: "text",
    0x03: "textStyle",
    0x04: "textFont",
    0x05: "textHeight",
    0x06: "textAlign",
    0x07: "textSize",
    0x08: "picture",
    0x09: "hilite",
    0x0A: "number",
    0x0B: "size",
    0x0C: "loop",
    0x0D: "duration",
    0x0E: "controller",
    0x0F: "directToStage",
    0x10: "sound",
    0x11: "foreColor",
    0x12: "backColor",
}
